### ISSUE TITLE
Smeagle model does not account for CV qualified types

### ISSUE THREAD

**Issue by vsoch** [spack/Smeagle#102]
E.g., "thing thing being pointed to" direction (import/export/something else) is hugely influenced by these.

```bash
char * const 
```
vs
```bash
char const * 
```
The first one is a constant pointer to a char, second is pointer to a constant char.  Right now our facts.json have constant represented, we made a first shot effort to add a check for this (but it needs more testing).

**Comment by hainest** [comment]
Ignore cv-qualified types.
